# Generated by Django 4.2 on 2023-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_billno_billtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('pdf', models.FileField(upload_to='static/bills/')),
            ],
        ),
        migrations.AlterField(
            model_name='billno',
            name='billtotal',
            field=models.BigIntegerField(),
        ),
    ]
