# Generated by Django 4.2 on 2023-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_generatedbills_alter_billno_billtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedbills',
            name='pdf',
            field=models.FileField(upload_to='static/'),
        ),
    ]
